### ISSUE TITLE
How to change the value of ViolinColor?

### ISSUE THREAD

**Issue by ludwig1860** [bastibe/Violinplot-Matlab#10]
Hi, Bastibe,
On the usage of violinplot function, I don't know how to set customer-defined color for violinColor property. Could you give me an example? 
Linyuan

**Comment by bastibe** [comment]
Try `help violinplot`. It works like any other Matlab function, e.g `violinplot(yourdata, 'violinColor', [1 0 0])`.

**Comment by ludwig1860** [comment]
I tried to assign two violins as two different colours, but the syntax violinplot(mydata, 'ViolinColor', [1 0 0;0 1 0]) doesn't work. The error reports "Color value must be a 3 element numeric vector".  But if the value should be 3-element vector, how can I set different colours for each?
Thanks a lot
Linyuan

**Comment by bastibe** [comment]
In that case `violinplot` returns two `Violin` objects, each of which have a `ViolinColor` property.

i.e.
```octave
vs = violinplot(...);
vs{1}.ViolinColor = [1 0 0];
vs{2}.ViolinColor = [0 1 0];
```

**Comment by ludwig1860** [comment]
Great! I got it. By the way, the brace should be parenthesis because vs is not a cell array. A pretty function! Thanks a lot.

**Comment by bastibe** [comment]
Cool, thanks.

If you want to, I'd be grateful for a pull request that adds this gotcha to an FAQ section in the README.
