### ISSUE TITLE
Question about optional values

### ISSUE THREAD

**Issue by davidsoltysik** [bastibe/Violinplot-Matlab#12]
Hi. This is a great tool. I just have a question about how to specify the options.

How do you specify options for 'ShowData', 'ShowNotches', and 'ShowMean'? I've tried 0, 'true', and 'false', but none of these work.

Thanks.

**Comment by bastibe** [comment]
Like the documentation says, `true` and `false` (or 0 and 1) should work.

**Comment by sg-s** [comment]
@davidsoltysik you should never use `'true'` or `'false'` because they both evaluate to `true`
