### ISSUE TITLE
Coloring of individual violins in multiple plotted violin plots

### ISSUE THREAD

**Issue by Rakshit1701** [bastibe/Violinplot-Matlab#13]
Hello,
Thank you for the wonderful code. I am plotting 18 data sets together, and I want some of the violins to have the same color. How do I set violin colors for each data set specifically using the 'ViolinColor' command?

Thank you.

**Comment by sriramb24** [comment]
Thanks for sharing this elegant code. 
I have the same question as the previous user. I tried providing a matrix of RGB values, but it looks like the code parses one color at a time and I am not proficient in obj oriented programming to get it to work for me. It works when only one RGB is provided as an input parameter, but it would be great if we can provide an equal number of color vectors as the data categories. 
Thanks much!

**Comment by Rakshit1701** [comment]
Hi Sriram,
I found a way to get a different colored plot for each dataset. I used the Violin instead of violin plot which lets you customize more parameters. Please find the lines attached below.

h1 = Violin(D1(:,1),0.5,'Width',0.2,'ViolinColor',[1,0.5,0],'ShowMean',true);hold on;
h2 = Violin(D1(:,2),1,'Width',0.2,'ViolinColor',[0.1,0.8,0.1],'ShowMean',true);hold on;
h3 = Violin(D1(:,3),1.5,'Width',0.2,'ViolinColor',[0, 0.4470, 0.7410],'ShowMean',true);

I have plotted each dataset by defining colors for each. Also, you can set xtick label positioning to make the plots more clear with the following command, if you are plotting each dataset separately using the Violin command. 

set(gca,'xtick',0:0.5:12,'xlim',[0 12],'ylim',[0 400]);

Hope this is helpful for you. Good Luck.

**Comment by sriramb24** [comment]
Thanks, Rakshit. That's a great idea. It works for me too!

**Comment by bastibe** [comment]
Alternatively, you can call `violinplot` as you normally would. It returns an array of violins. After that, you can set the `ViolinColor` of each violin like this:

```matlab
violins = violinplot(...);
violin(1).ViolinColor = [1, 0.5, 0];
violin(2).ViolinColor = [0.1, 0.8, 0.1];
% etc...
```

**Comment by sriramb24** [comment]
Thanks, bastibe. I used these plots in my manuscript and acknowledged this repo.

**Comment by bastibe** [comment]
Cool, thank you!
