### ISSUE TITLE
Coloring groupings 

### ISSUE THREAD

**Issue by christoffermattssonlangseth** [bastibe/Violinplot-Matlab#15]
Hi guys, 

Thank you for a helpful tool to make violin plots. I have a quick question regarding coloring and specifically how to color based on a predefined group. I have attach an example down below: 

![image](https://user-images.githubusercontent.com/47141935/63768194-dd69e180-c8cf-11e9-8edc-28d7a64cff6a.png)

In this case, I would like to order the first two with the same color, but separate violins. The same would be done with 3 and 4 and so on and so forth. 

All the best, 
Christoffer

**Comment by christoffermattssonlangseth** [comment]
It would be very nice to do it in a similar way as the GroupOrder is done, i.e. in a cell.

**Comment by bastibe** [comment]
Sorry for the late response, I was on vacation.

The `violinplot` command returns an array of Violins, and you can customize the color of each Violin.

**Comment by JDthompson15** [comment]
I've been having the same issue and can't figure out how to use the 'ViolinColor' parameter to do this. Could you provide an example?

**Comment by bastibe** [comment]
```matlab
load carbig MPG Origin % load some example data
Origin = string(Origin);
figure
violins = violinplot(MPG, Origin);
violins(2).ViolinColor = [1 0 0]; % make the second violin red
```

**Comment by hettk** [comment]
Thank you for this awesome tool!

**Comment by bastibe** [comment]
You are very welcome!

**Comment by hillhillll** [comment]
got it, thanks

**Comment by bastibe** [comment]
Are you, by any chance, running a very old version of Matlab? `colororder` was introduced in 2019b.

**Comment by pcpollak** [comment]
Yes I am running 2019a
Thank you for pointing this out!
