### ISSUE TITLE
'ksdensity' requires Statistics and Machine Learning Toolbox.

### ISSUE THREAD

**Issue by bababash** [bastibe/Violinplot-Matlab#17]
Is there an open source implementation of this?

```
Error in Violin (line 118)
            [density, value] = ksdensity(data, 'bandwidth', args.Bandwidth);
Error in violinplot (line 115)
            violins(n) = Violin(thisData, n, varargin{:}); 
```

**Comment by bastibe** [comment]
None that I'm aware of, sorry.

**Comment by bababash** [comment]
In case you're interested, this open source toolbox is able to do them: [https://github.com/IoSR-Surrey/MatlabToolbox/blob/master/%2Biosr/%2Bstatistics/boxPlot.m](https://github.com/IoSR-Surrey/MatlabToolbox/blob/master/%2Biosr/%2Bstatistics/boxPlot.m)

**Comment by bastibe** [comment]
For posterity, this is their kernel density estimate: https://github.com/IoSR-Surrey/MatlabToolbox/blob/master/%2Biosr/%2Bstatistics/kernelDensity.m
