### ISSUE TITLE
Properties Are Ignored in Case of Matrix Data

### ISSUE THREAD

**Issue by RoyiAvital** [bastibe/Violinplot-Matlab#2]
If the user sends the data in a Matrix form the functions ignores the properties the user set as input.

See https://github.com/bastibe/Violinplot-Matlab/blob/master/violinplot.m#L92.

By the way, could you specify the form of the properties you expect?
For instance, let's say I create 24 columns matrix and want to set each group color, what is the form of 'ViolinColor'? Is it a 24x3 Matrix of RGB colors?

Thank You.

**Comment by bastibe** [comment]
Sorry for not responding. I must have overlooked this issue.

In matrix form, `violinplot` creates one violin per row and returns a vector of `Violin` objects. This is analogous to how `boxplot` works. You can set properties on each `Violin` object separately after invoking `violinplot`. Alternatively, it might be easier to forego `violinplot` entirely, and create the `Violin` objects manually.

**Comment by RoyiAvital** [comment]
But what if I want to set parameters for a matrix within the call for `violinplot`?

For instance, what should be the form of `ViolinColor`?

**Comment by bastibe** [comment]
This is currently not supported. In my opinion, building this for every property would be error-prone and hard to document, while not providing much utility to end users. It is conceptually much easier to use `Violin` instead, or to modify the `Violin`s as returned from `violinplot`.

**Comment by RoyiAvital** [comment]
I see.
So for many rows matrix one should just display it and then edit the properties of each element.

I think it should be documented.

Thank You.

**Comment by bastibe** [comment]
Wait, I think I understand your question now: The documentation says that the function parameters are applied to all violins, which is clearly not the case. This is a bug, and I'll fix it.

**Comment by RoyiAvital** [comment]
Also the documentation states that each column is a set of samples, not a row.

**Comment by bastibe** [comment]
Should be fixed now. Can you check if this solves your problem? You still can't set *different* colors for different rows, but at least you can provide a uniform color, or uniformly switch features on or off.

**Comment by bastibe** [comment]
> Also the documentation states that each column is a set of samples, not a row.

Should be fixed, as well.

**Comment by piby2** [comment]
Has this issue been fixed? Do you have any example how to use the attributes such as "ShowMeans" in case of a matrix? Thanks

**Comment by bastibe** [comment]
Does `violinplot(data, 'ShowMeans', true)` work?

**Comment by piby2** [comment]
> Does `violinplot(data, 'ShowMeans', true)` work?

No, I get this error.
Error using Violin/checkInputs (line 307)
Expected a string for the parameter name, instead the input type was 'logical'.

Error in Violin (line 105)
            args = obj.checkInputs(data, pos, varargin{:});

Error in violinplot (line 94)
            violins(n) = Violin(thisData, n, varargin{:});

**Comment by bastibe** [comment]
how about `violinplot(data, [], 'ShowMeans', true)`?

**Comment by piby2** [comment]
> how about `violinplot(data, [], 'ShowMeans', true)`?

That works! Thank you. Please update the readme if possible.

**Comment by bastibe** [comment]
This is standard Matlab syntax, and documented in `help violinplot`.
