### ISSUE TITLE
Disable subscript for '_' from cat

### ISSUE THREAD

**Issue by shalailahaas** [bastibe/Violinplot-Matlab#20]
Hi, 
I was just wondering if there is a way to disable the automatic subscripting for labels when using underscore ('_') for categories in your script? I know the general usage is to add 'Interpreter', 'none' but I am not sure where to add this in the function so that it prints my category labels without subscripting the underscore. 
I tried adding it here:
set(gca, 'XTick', 1:length(catnames), 'XTickLabels', catnames, 'Interpreter', 'none'); 
But this makes no difference. 

For example, two of my categories are "Bern_1" and "Maastricht_1". 
I was hoping to retain the underscores. 

Thank you for your help!

**Comment by bastibe** [comment]
This is entirely up to Matlab. The violinplot merely sets the XTickLabels to your category names: https://github.com/bastibe/Violinplot-Matlab/blob/master/violinplot.m#L88. It doesn't change how Matlab renders them.

If you want to change how Matlab renders XTickLabels, you have to do it in your own code.
