### ISSUE TITLE
Trouble passing arguments

### ISSUE THREAD

**Issue by DeshmukhLab** [bastibe/Violinplot-Matlab#26]
The violin plots look great! Thank you.

Edit: nevermind. I figured out the mistake I was making - I was forgetting to pass the argument for cats: I was using violinplot(allmeanrate,'EdgeColor',[1 1 1]); instead of violinplot(allmeanrate,[],'EdgeColor',[1 1 1]);

While the barebones violinplot(data) works without trouble, I am having trouble passing arguments to  violinplot:

violinplot(allmeanrate,'EdgeColor',[1 1 1]);

Error using Violin/checkInputs (line 342)
Expected a string scalar or character vector for the
parameter name.

Error in Violin (line 106)
            args = obj.checkInputs(data, pos,
            varargin{:});

Error in violinplot (line 86)
            violins(n) = Violin(thisData, n,
            varargin{:});

What am I doing wrong?

**Comment by bastibe** [comment]
Please reopen if you still need help.
