### ISSUE TITLE
unmodifiable plots

### ISSUE THREAD

**Issue by guncha06** [bastibe/Violinplot-Matlab#32]
hi,
i was wondering why the matlab figure generated by this code is not modifiable in other softwares such as illlustrator wheras other matlab figures generated are (in eps format). is there a way to plot the violin plots such that it is not generated as an image in eps ( and hence unmodifiable in illustrator)?? i wanted it that way to modify certain aspects of the plots to make it more suitable and clean for a publication.

**Comment by bastibe** [comment]
No idea, sorry. Matlab does what matlab does. There is certainly nothing this package is doing to specifically disable editing.
