### ISSUE TITLE
Only Support 7 colors

### ISSUE THREAD

**Issue by Ruida-Xie** [bastibe/Violinplot-Matlab#35]
The plot style is beautiful.

One issue I experienced: It only supports seven items.

For example: I have a matrix of n*8 to plot. If I cutmomize 8 'ViolinColors', then it wont have any error message, but it also won't plot the 8th column. If I left the 'ViolinColors' to default, then :

`Index in position 1 exceeds array bounds. Index must not exceed 7.

Error in Violin (line 272)
                    ViolinColor{1} = args.ViolinColor{1}(pos,:);`

I checked the code, this error is because in line 148 in "Violin.m", if the 'ViolinColors' is undefined, then you use  C = colororder;. By default, it only has 7 colors. Hope this can be improved.

Regards,
Ruida

**Comment by bastibe** [comment]
It uses Matlab's default color order. That's the correct thing to do. 

If you want different colors, you can either set your own custom colors on the Violins, or probably globally set a different default color order.
