### ISSUE TITLE
LICENSE missing!

### ISSUE THREAD

**Issue by cunyap** [bastibe/Violinplot-Matlab#39]
Hi,

Great work. I would like to use your toolbox in my work. However, since your project is missing a License I (and everyone) can not use your work in larger projects which require your tool to be integrated i.e. as submodule or as a derivative.

Could you please add a LICENSE?

Thanks!

**Comment by bastibe** [comment]
The source files mention that the source code is licensed under the terms of the BSD 3-clause license. But for your convenience, I added an explicit LICENSE file.
