### ISSUE TITLE
interp1 error

### ISSUE THREAD

**Issue by rebecca-mease** [bastibe/Violinplot-Matlab#46]
Hi, thank you for your great package!

I am using 2022a and get the following error for both the test calls and my own data 
![image](https://user-images.githubusercontent.com/4683547/172661930-73e711e4-3a02-46af-8093-90906f7cbdbe.png)

It seems that the unique values for `density `and `value `returned from `calcKernelDensity ` sometimes have different number of elements

There is also an issue with `data` having repeat values, this also causes an error with interp1.

For now I have perhaps fixed the problems with `
 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/4683547/172663205-83cac48a-6a1a-4c1f-92e1-a83c2adedac1.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/4683547/172663328-d6c4f926-0ca8-4808-a0ee-205633fdd93e.png">

But you likely have a better way of handling these issues--thank you again for such a useful tool!

**Comment by mikelgg93** [comment]
Thanks for bringing this up, I have been quite busy and did not have time to properly test the unique, but that´s definitely a regression. Also thanks for suggesting a solution, I will check it up and come back ASAP.

**Comment by mikelgg93** [comment]
I have removed the "unique". I won't have time until next week to look it up more in detail. However, you can try if just modifying value in the cal density solved. Again thanks, and apologies for the regression.

**Comment by mikelgg93** [comment]
> Thanks for the nice work!
> 
> Regarding the non-unique sample points in the interp1 function, I would suggest calculating unique indices for the values only and using the same indices for the density, i.e. replacing [line 204](https://github.com/bastibe/Violinplot-Matlab/blob/62d748f16c33a122e2033187b103f26ced1114a4/Violin.m#L204) by `[~, unique_idx] = unique(value);` `jitterstrength = interp1(value(unique_idx), density(unique_idx)*width, data, 'linear','extrap');`
> 
> Same for [line 317](https://github.com/bastibe/Violinplot-Matlab/blob/62d748f16c33a122e2033187b103f26ced1114a4/Violin.m#L317).

Hi! Thanks for the suggestion, did not #47 solve already this, by just throwing a single value (Line 698 at Violin.m) at calcKernelDensity if the values were the same?

**Comment by thomasdeppisch** [comment]
> Hi! Thanks for the suggestion, did not #47 solve already this, by just throwing a single value (Line 698 at Violin.m) at calcKernelDensity if the values were the same?

The fix at line 698 only applies if all entries in the `data` are the same. However, there could be three values in data of which two are the same, creating the non-uniqueness error. (In such a case, simply taking the mean does as far as I can see not make much sense, so the proposed solution above might be beneficial.)

**Comment by mikelgg93** [comment]
Indeed, I will add your changes. Thanks @thomasdeppisch

**Comment by rebecca-mease** [comment]
Thanks for the fix and the great package!
