### ISSUE TITLE
Error with structure input format

### ISSUE THREAD

**Issue by OmarKhater-sws** [bastibe/Violinplot-Matlab#48]
I have data of the form:
` 
data = struct('Group1', rand(10,1), 'Group2', rand(20,1));
`
I see it should plot them field by field. However, it seems like there is something wrong with the input validation (function results = checkInputs(~, data, pos, varargin)). More specifically, parsing this line raises an error 
```
p.addRequired('Data', @(x)isnumeric(vertcat(x{:})));
```
It is not clear for me why you do cell indexing while you accept the input in matrix format.

**Comment by mikelgg93** [comment]
It will be fixed in the next commit, the error was on the `violinplot.m` function.

`Line 135`  should be `violins(n) = Violin({thisData}, n, varargin{:}); `
instead it was `violins(n) = Violin(thisData, n, varargin{:}); `.

Thanks for pointing this out.
