### ISSUE TITLE
How to hide data points?

### ISSUE THREAD

**Issue by Youguang** [bastibe/Violinplot-Matlab#5]
Is this way?
`violinplot(mydatastructure,'ShowData',0) `

Thank you.

**Comment by bastibe** [comment]
yes.

**Comment by Youguang** [comment]
Error using Violin/checkInputs (line 292)
Expected a string scalar or character vector for the parameter name, instead the input type was 'double'.

Error in Violin (line 105)
            args = obj.checkInputs(data, pos, varargin{:});

Error in violinplot (line 70)
            violins(n) = Violin(thisData, n, varargin{:});

**Comment by bastibe** [comment]
You are not giving me enough information to answer your question. Please write a complete and well-formed question, and give all relevant data. Otherwise, I can't help you.

https://stackoverflow.com/help/how-to-ask
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

**Comment by Youguang** [comment]
```
test=struct('a', [1:100],'b',[50:150],'c',[100:200]);
set(gca, 'colororder',[0.9 0.5 0.5; 0.5 0.7 0.8; 0.4 0.4 0.4]);
violinplot(test)
```
ERROR 1, the colour order is a c b, not a b c.

`violinplot(test,'ShowData',0)`

ERROR 2:
```
Error using Violin/checkInputs (line 292)
Expected a string scalar or character vector for the parameter name, instead the input type was 'double'.

Error in Violin (line 105)
            args = obj.checkInputs(data, pos, varargin{:});

Error in violinplot (line 70)
            violins(n) = Violin(thisData, n, varargin{:});
```
