### ISSUE TITLE
Changing the parameters when plotting a structure

### ISSUE THREAD

**Issue by stefanknoops** [bastibe/Violinplot-Matlab#51]
Hi guys, 

Thanks for this package, it works great! 

One thing I can not figure out though, is how to change parameters when plotting a structure. Right now, I write something like `violinplot(ErrorList,'DataStyle','none')`

However that gives me the error that no value is given for 'none'. What is the correct way of plotting this? ErrorList has a variable amount of items, so I would prefer not looping over all Violins

**Comment by mikelgg93** [comment]
The second input parameter of the violinplot is the categories, to do what you want to do, you need to call it like:
`violinplot(ErrorList, [], 'DataStyle','none');`

**Comment by stefanknoops** [comment]
Great, thanks!
