### ISSUE TITLE
Different shapes of plot for very similar data

### ISSUE THREAD

**Issue by mirkabuist** [bastibe/Violinplot-Matlab#52]
I am plotting a 6 violinplots for relativly similar sets of data. One out of 6 plots has a very different shape from the other ones. I am not sure why.
![image](https://user-images.githubusercontent.com/108273328/175930260-9b3b8a49-e57e-4196-b03a-9c2cead61026.png)
As you can see in the image, most of them are very slim and curved around the datapoints, whereas the second plot is very wide and doesn't follow the datapoints as neathly as the others.

I use the code:
violinplot(MFTtablectrl, {"Pre", "Post", "Follow-up"},'HalfViolin','full','ShowMean', true, 'DataStyle', 'scatter')
where MFTtablectrl is a 32x3 double with a variety of the values [0.008, 0.07, 0.04, 0.02, 0.16, 0.4]

**Comment by mikelgg93** [comment]
Hi @mirkabuist 
There seems to be something off with the Post-Control. Can you share the data for replication? Just the post control should be enough, then I will take a look.

**Comment by mirkabuist** [comment]
Hi, I will share the data for the first 2 plots (Pre-control & Post-Control), these are the first to columns of the double "MFTtablectrl":

Pre-Control:
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.0200000000000000
0.0400000000000000
0.0700000000000000
0.0200000000000000
0.160000000000000
0.400000000000000
0.0200000000000000
0.0200000000000000
0.00800000000000000
0.160000000000000
0.0700000000000000
0.160000000000000
0.0700000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.0700000000000000
0.00800000000000000
0.0700000000000000
0.0200000000000000
0.0200000000000000
0.0400000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.0200000000000000
0.00800000000000000
0.00800000000000000


Post Control:
0.0400000000000000
0.0400000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.0400000000000000
0.0700000000000000
0.00800000000000000
0.00800000000000000
0.0400000000000000
0.0700000000000000
0.160000000000000
0.0200000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.0200000000000000
0.00800000000000000
0.400000000000000
0.400000000000000
0.0200000000000000
0.0200000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000
0.00800000000000000


This results in the following plot:
![image](https://user-images.githubusercontent.com/108273328/176452728-a0d427f5-0f83-422f-8e05-8de94d3d61c5.png)

**Comment by mikelgg93** [comment]
@mirkabuist apologies for coming back so late. I have been quite busy. 
It seems like a problem with the kernel density computation, as your data has not too much variety.
You can work around it using the "BandWith" parameter, for example:

```
vs_pre = Violin({pre},...
    1,...
    'HalfViolin','full',...% left, full
    'QuartileStyle','none',... % boxplot, none
    'DataStyle', 'scatter',... % scatter, none
    'BandWidth', .025,...
    'ShowNotches', false,...
    'ShowMean', true,...
    'ShowMedian', true)

vs_post = Violin({post},...
    2,...
    'HalfViolin','full',...% left, full
    'QuartileStyle','none',... % boxplot, none
    'DataStyle', 'scatter', ... % scatter, non
    'BandWidth', .025,...
    'ShowNotches', false,...
    'ShowMean', true,...
    'ShowMedian', true)
```
![image](https://user-images.githubusercontent.com/11683112/178261771-c471bec0-cfae-4381-8818-6ec7ba35d755.png)

**Comment by mirkabuist** [comment]
Perfect, that works!
Thanks a lot.
