### ISSUE TITLE
Whiskers are not accurate

### ISSUE THREAD

**Issue by sharahamo** [bastibe/Violinplot-Matlab#6]
@bastibe For some data the whiskers are not accurate. Superimposing violin plot over boxplot shows that the whiskers for violin plot is sometimes longer than the whiskers of MATLAB's boxplot function

I find this true when there are outliers in the data -- violinplot does not consider outliers
<img width="442" alt="screen shot 2018-05-31 at 15 59 22" src="https://user-images.githubusercontent.com/8395313/40789977-9e2af052-64eb-11e8-9cf0-1a70906414bf.png">

**Comment by bastibe** [comment]
Thank you for finding this bug. It has been fixed in 1b72d33c3648347b3fd17e99c422f7659f84e522. I missed is a quirk in how boxplot calculates the whisker size: It is not quite quantile_25-1.5*(quantile_74-quantile_25), but only extends to the maximum value that is not an outlier.

**Comment by sharahamo** [comment]
Absolutely amazing. Thank you for the fix.
