### ISSUE TITLE
Ugly display when using yyaxis left/right

### ISSUE THREAD

**Issue by NicolasClairis** [bastibe/Violinplot-Matlab#66]
When using yyaxis left and/or right to have data with different frames, the display of the violin plot suddenly becomes very ugly for some reason. Any way to fix this to be able to use that feature without losing in display quality?

See example in the image below (the 4 first violins were done without specifying anything while the two last violins were displayed after calling yyaxis right since their range is very different but weird circles appear along the violin in the right and the trait is a dotted line for the violin in the left instead of a continuous like in the other violins, and I have no idea why these changes were performed when calling yyaxis right
![image](https://github.com/bastibe/Violinplot-Matlab/assets/15351232/67845f9a-e244-4299-a9c9-cd589612ceaf)

**Comment by NicolasClairis** [comment]
I see that the issue has already been raised here https://github.com/bastibe/Violinplot-Matlab/issues/59 and the suggested solution was this

> That is very strange indeed. Perhaps we should just `set(obj.ViolinPlot, "Marker", "none")` and `set(obj.ViolinPlot2, "Marker", "none")` at the very end of the Violin constructor, just to be safe.

so I added these two lines within lines 415-416 of Violin and it does solve the issue of weird circles around the violin, but the dotted lines are still here so I guess this is a different bug
![image](https://github.com/bastibe/Violinplot-Matlab/assets/15351232/0a19a17f-a4a5-4ffd-8bef-01cc52b0697b)

**Comment by NicolasClairis** [comment]
I just added a pull request accordingly

**Comment by NicolasClairis** [comment]
@bastibe any idea as to why the third blue violin has a dotted line and not the others? Once this is fixed and the pull request for the markers around the violins is accepted, this issue can be closed on my side :)

**Comment by bastibe** [comment]
No idea. Perhaps we need to add an explicit line style for the center line? Something sure seems to have changed in Matlab with regards to default stylings.

**Comment by NicolasClairis** [comment]
Ok I found the fix for the edges (since the line style is not specified, it seems that matlab automatically decides to change line style when calling the "yyaxis left/right" function for some reason. The fix is to add `,'LineStyle','-'` when calling the fill function. I'm going to add a pull request accordingly. However, this does not solve all the problems.
In the example below, I still have some major issues:
- presence of stars and dotted lines for the second (2nd violin called with yyaxis left) and fourth (2nd violin called with yyaxis right) violin
- weird huge grey circles at the borders of the first (1st violin called with yyaxis left) and third (1st violin called with yyaxis right) violins

I suspect that these issues are of the same order (some parameter automatically entered by matlab since no default value is entered in the script and for some reason this only happens when calling yyaxis left/right. I'm still digging to find the origin of the problem
![image](https://github.com/bastibe/Violinplot-Matlab/assets/15351232/3fbd6c73-6105-40e3-a26b-e9a8f9f059c0)

**Comment by NicolasClairis** [comment]
Ok I think I finally fixed it. Indeed, the problem was just to manually force the script to always have no Marker and a continuous line for both the boxplot in the middle and for the violin fill around. These changes seem to fix the problem.

**Comment by bastibe** [comment]
Thank you very much for looking into this!

Do you happen to know why we have to specify a marker in some cases, but not others? Perhaps it would be a good idea to just _always_ define a marker and line style.

**Comment by NicolasClairis** [comment]
No idea but my guess is that matlab functions reset the `Marker `and `LineStyle `function everytime you call `Violin `when you don't use this `yyaxis `option, but they don't when you call `yyaxis left/right` so that it goes to the next option for both and that creates these weird displays. Indeed, fixing the `Marker `option to "none" and `LineStyle `to "-" by default for all calls to `fill `and `plot ` seems to fix the problems. I will close the issue accordingly.
