### ISSUE TITLE
plot 2 violin plot in one gourp

### ISSUE THREAD

**Issue by jackxuxu** [bastibe/Violinplot-Matlab#72]
how can we do this? Thanks a lot. 

![A-Violin-plots-showing-the-distribution-of-body-weight-and-B-Normalized-heart-weight](https://github.com/bastibe/Violinplot-Matlab/assets/1006131/9b7952d1-52c1-4ddf-9f08-1dfbff711b9a)

**Comment by mikelgg93** [comment]
@jackxuxu  You can directly call `Violin` and pass the position argument (https://github.com/bastibe/Violinplot-Matlab/blob/master/Violin.m#L108-L111). 

Thus, you could place those violin plots, e.g. on 0.5 and 1.5 and then define the `xticks` and labels to be at 1.(https://www.mathworks.com/help/matlab/creating_plots/change-tick-marks-and-tick-labels-of-graph-1.html)
